root: true
parser: '@typescript-eslint/parser'
extends:
  - prettier
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
settings:
  react:
    version: 18.x